export default {
  // Fetch Examples
  EXAMPLE_FETCH_REQUEST: 'EXAMPLE_FETCH_REQUEST',
  EXAMPLE_FETCH_SUCCESS: 'EXAMPLE_FETCH_SUCCESS',
  EXAMPLE_FETCH_FAIL: 'EXAMPLE_FETCH_FAIL',
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
  USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',
  PAYMENT_TOKEN_REQUEST: 'PAYMENT_TOKEN_REQUEST',
  PAYMENT_TOKEN_SUCCESS: 'PAYMENT_TOKEN_SUCCESS',
  PAYMENT_TOKEN_FAILED: 'PAYMENT_TOKEN_FAILED',
  PAYMENT_CHARGE_REQUEST: 'PAYMENT_CHARGE_REQUEST',
  PAYMENT_CHARGE_SUCCESS: 'PAYMENT_CHARGE_SUCCESS',
  PAYMENT_CHARGE_FAILED: 'PAYMENT_CHARGE_FAILED',
  PAYMENT_GET_INFO_REQUEST: 'PAYMENT_GET_INFO_REQUEST',
  PAYMENT_GET_INFO_SUCCESS: 'PAYMENT_GET_INFO_SUCCESS',
  PAYMENT_GET_INFO_FAILED: 'PAYMENT_GET_INFO_FAILED',
  USER_GET_INFO_REQUEST: 'USER_GET_INFO_REQUEST',
  USER_GET_INFO_SUCCESS: 'USER_GET_INFO_SUCCESS',
  USER_GET_INFO_FAILED: 'USER_GET_INFO_FAILED'
};
