export default {
  // Fetch Examples
  EXAMPLE_FETCH_REQUEST: 'EXAMPLE_FETCH_REQUEST',
  EXAMPLE_FETCH_SUCCESS: 'EXAMPLE_FETCH_SUCCESS',
  EXAMPLE_FETCH_FAIL: 'EXAMPLE_FETCH_FAIL',
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
  USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',
  SET_TRADE_TOKEN: 'SET_TRADE_TOKEN_REQUEST',

  PAYMENT_TOKEN_REQUEST: 'PAYMENT_TOKEN_REQUEST',
  PAYMENT_TOKEN_SUCCESS: 'PAYMENT_TOKEN_SUCCESS',
  PAYMENT_TOKEN_FAILED: 'PAYMENT_TOKEN_FAILED',
  PAYMENT_CHARGE_REQUEST: 'PAYMENT_CHARGE_REQUEST',
  PAYMENT_CHARGE_SUCCESS: 'PAYMENT_CHARGE_SUCCESS',
  PAYMENT_CHARGE_FAILED: 'PAYMENT_CHARGE_FAILED',
  PAYMENT_GET_INFO_REQUEST: 'PAYMENT_GET_INFO_REQUEST',
  PAYMENT_GET_INFO_SUCCESS: 'PAYMENT_GET_INFO_SUCCESS',
  PAYMENT_GET_INFO_FAILED: 'PAYMENT_GET_INFO_FAILED',
  USER_GET_INFO_REQUEST: 'USER_GET_INFO_REQUEST',
  USER_GET_INFO_SUCCESS: 'USER_GET_INFO_SUCCESS',
  USER_GET_INFO_FAILED: 'USER_GET_INFO_FAILED',
  BUYIN_STACKE_REQUEST: 'BUYIN_STACKE_REQUEST',
  BUYIN_STACKE_SUCCESS: 'BUYIN_STACKE_SUCCESS',
  BUYIN_STACKE_FAILED: 'BUYIN_STACKE_FAILED',

  GET_ACTIVE_GAME_ROOM_REQUEST: 'GET_ACTIVE_GAME_ROOM_REQUEST',
  GET_ACTIVE_GAME_ROOM_SUCCESS: 'GET_ACTIVE_GAME_ROOM_SUCCESS',
  GET_ACTIVE_GAME_ROOM_FAILED: 'GET_ACTIVE_GAME_ROOM_FAILED',

  CREATE_ROOM_REQUEST: 'CREATE_ROOM_REQUEST',
  CREATE_ROOM_SUCCESS: 'CREATE_ROOM_SUCCESS',
  CREATE_ROOM_FAILED: 'CREATE_ROOM_FAILED',

  JOIN_ROOM_REQUEST: 'JOIN_ROOM_REQUEST',
  JOIN_ROOM_SUCCESS: 'JOIN_ROOM_SUCCESS',
  JOIN_ROOM_FAILED: 'JOIN_ROOM_FAILED',

  LEADER_BOARD_SCORE_LIST_REQUEST: 'LEADER_BOARD_SCORE_LIST_REQUEST',
  LEADER_BOARD_SCORE_LIST_SUCCESS: 'LEADER_BOARD_SCORE_LIST_SUCCESS',
  LEADER_BOARD_SCORE_LIST_FAILED: 'LEADER_BOARD_SCORE_LIST_FAILED'

};
