export default {
  // Fetch Examples
  EXAMPLE_FETCH_REQUEST: 'EXAMPLE_FETCH_REQUEST',
  EXAMPLE_FETCH_SUCCESS: 'EXAMPLE_FETCH_SUCCESS',
  EXAMPLE_FETCH_FAIL: 'EXAMPLE_FETCH_FAIL',
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
  USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED'
};
